# Configuration for PR labeler (actions/labeler@v5)
# https://github.com/actions/labeler

'status:awaiting review':
  - changed-files:
      - any-glob-to-any-file: '**/*'

'component:swift sdk':
  - changed-files:
      - any-glob-to-any-file: '**/*.swift'
      - any-glob-to-any-file: '**/*.xcodeproj/**'
      - any-glob-to-any-file: '**/Package.swift'
      - any-glob-to-any-file: '**/Package.resolved'
