name: check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Whitespace
        run: scripts/check_whitespace.sh

      - name: Check Filename Spaces
        run: scripts/check_filename_spaces.sh

      - name: Check Copyrights
        run: scripts/check_copyright.sh
