name: Whisper Caption Pro Build, Test & Archive

on:
  pull_request:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-archive-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Initialize xcodebuild
        run: xcodebuild -list -project WhisperCaptionPro/WhisperCaptionPro.xcodeproj

      - name: Test the Whisper Caption Pro
        run: |
          xcodebuild \
            -project WhisperCaptionPro/WhisperCaptionPro.xcodeproj \
            -scheme "WhisperCaptionPro" \
            -sdk macosx \
            -destination 'platform=macOS' \
            test \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Build the Whisper Caption Pro
        run: |
          xcodebuild \
            -project WhisperCaptionPro/WhisperCaptionPro.xcodeproj \
            -scheme "WhisperCaptionPro" \
            -sdk macosx \
            -destination 'platform=macOS' \
            build \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Archive the Whisper Caption Pro
        run: |
          xcodebuild \
            -project WhisperCaptionPro/WhisperCaptionPro.xcodeproj \
            -scheme "WhisperCaptionPro" \
            -sdk macosx \
            -destination 'platform=macOS' \
            archive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY=""
