name: Whipser Caption Pro

on:
  pull_request:
  schedule:
    # Run every day at 11pm (KST) - cron uses UTC times
    - cron:  '0 14 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  swift-build-run:
    strategy:
      matrix:
        # Test build with debug and release configs (whether or not DEBUG is set and optimization level)
        build: [build, archive]
        os: [macos-15]
        include:
          - os: macos-15
            xcode: Xcode_16.2
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Xcode
      run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app/Contents/Developer
    - name: Initialize xcodebuild
      run: xcodebuild -list -project WhipserCaptionPro/WhipserCaptionPro.xcodeproj
    - name: Build the Whipser Caption Pro
      run: scripts/third_party/travis/retry.sh scripts/build.sh WhipserCaptionPro macOS ${{ matrix.build }} WhipserCaptionPro/WhipserCaptionPro.xcodeproj
