name: Whisper Caption Pro Build, Test & Archive

on:
  pull_request:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-archive-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize xcodebuild
        run: xcodebuild -list

      - name: Test the Whisper Caption Pro
        run: |
          xcodebuild \
            -project WhisperCaptionPro/WhisperCaptionPro.xcodeproj \
            -scheme "WhisperCaptionPro" \
            -sdk macosx \
            -destination 'platform=macOS' \
            test

      - name: Build the Whisper Caption Pro
        run: |
          xcodebuild \
            -project WhisperCaptionPro/WhisperCaptionPro.xcodeproj \
            -scheme "WhisperCaptionPro" \
            -sdk macosx \
            -destination 'platform=macOS' \
            build

      - name: Archive the Whisper Caption Pro
        run: |
          xcodebuild \
            -project WhisperCaptionPro/WhisperCaptionPro.xcodeproj \
            -scheme "WhisperCaptionPro" \
            -sdk macosx \
            -destination 'platform=macOS' \
            archive
